version: '3.7'

services:
  web:
      build:
        context: buzzzon
        dockerfile: Dockerfile
      command: sh -c "./docker-entrypoint.sh"
      volumes:
        - static_volume:/usr/src/app/static/
        - media_volume:/usr/src/app/media/
      env_file:
        - .docker-compose.env
      ports:
        - 8000:8000
      depends_on:
      - db

  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - .docker-compose.env
      ports:
        - 5432:5432

  redis:
      image: "redis:alpine"

  daphne:
    build:
        context: buzzzon
        dockerfile: Dockerfile
    command: sh -c "daphne -b 0.0.0.0 -p 8005 buzzzon.asgi:application"
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    env_file:
      - .docker-compose.env
    ports:
        - "8005:8005"
    depends_on:
        - db
        - redis

  nginx:
    build:
      context: nginx
      dockerfile: nginx/Dockerfile
    command: nginx -g 'daemon off';
    volumes:
      - static_volume:/usr/src/app/buzzzon/static/
      - media_volume:/usr/src/app/buzzzon/media/
      - /data/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
    postgres_data:
    static_volume:
    media_volume:
