# Generated by Django 4.0 on 2023-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, 'chat'), (2, 'group_control'), (3, 'closed')], default=1),
        ),
    ]
